### ISSUE TITLE
RuntimeError when using swinv2 taggers

### ISSUE THREAD

**Issue by Volnovik** [toshiaki1729/stable-diffusion-webui-dataset-tag-editor#102]
**Describe the bug**
Error when using any swin based tagger:

Traceback (most recent call last):
  File "S:\StabilityMatrix\Packages\Stable Diffusion WebUI\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "S:\StabilityMatrix\Packages\Stable Diffusion WebUI\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "S:\StabilityMatrix\Packages\Stable Diffusion WebUI\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "S:\StabilityMatrix\Packages\Stable Diffusion WebUI\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "S:\StabilityMatrix\Packages\Stable Diffusion WebUI\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "S:\StabilityMatrix\Packages\Stable Diffusion WebUI\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "S:\StabilityMatrix\Packages\Stable Diffusion WebUI\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "S:\StabilityMatrix\Packages\Stable Diffusion WebUI\extensions\stable-diffusion-webui-dataset-tag-editor\scripts\tag_editor_ui\block_load_dataset.py", line 158, in load_files_from_dir
    dte_instance.load_dataset(
  File "S:\StabilityMatrix\Packages\Stable Diffusion WebUI\extensions\stable-diffusion-webui-dataset-tag-editor\scripts\dataset_tag_editor\dte_logic.py", line 797, in load_dataset
    tg.start()
  File "S:\StabilityMatrix\Packages\Stable Diffusion WebUI\extensions\stable-diffusion-webui-dataset-tag-editor\scripts\dataset_tag_editor\taggers_builtin.py", line 115, in start
    self.tagger_inst.load()
  File "S:\StabilityMatrix\Packages\Stable Diffusion WebUI\extensions\stable-diffusion-webui-dataset-tag-editor\scripts\dataset_tag_editor\interrogators\waifu_diffusion_tagger_timm.py", line 52, in load
    self.model: torch.nn.Module = timm.create_model(
  File "S:\StabilityMatrix\Packages\Stable Diffusion WebUI\venv\lib\site-packages\timm\models\_factory.py", line 114, in create_model
    model = create_fn(
  File "S:\StabilityMatrix\Packages\Stable Diffusion WebUI\venv\lib\site-packages\timm\models\swin_transformer_v2.py", line 763, in swinv2_base_window8_256
    return _create_swin_transformer_v2(
  File "S:\StabilityMatrix\Packages\Stable Diffusion WebUI\venv\lib\site-packages\timm\models\swin_transformer_v2.py", line 636, in _create_swin_transformer_v2
    model = build_model_with_cfg(
  File "S:\StabilityMatrix\Packages\Stable Diffusion WebUI\venv\lib\site-packages\timm\models\_builder.py", line 381, in build_model_with_cfg
    model = model_cls(**kwargs)
  File "S:\StabilityMatrix\Packages\Stable Diffusion WebUI\venv\lib\site-packages\timm\models\swin_transformer_v2.py", line 524, in __init__
    layers += [SwinTransformerV2Stage(
  File "S:\StabilityMatrix\Packages\Stable Diffusion WebUI\venv\lib\site-packages\timm\models\swin_transformer_v2.py", line 410, in __init__
    self.blocks = nn.ModuleList([
  File "S:\StabilityMatrix\Packages\Stable Diffusion WebUI\venv\lib\site-packages\timm\models\swin_transformer_v2.py", line 411, in <listcomp>
    SwinTransformerV2Block(
  File "S:\StabilityMatrix\Packages\Stable Diffusion WebUI\venv\lib\site-packages\timm\models\swin_transformer_v2.py", line 275, in __init__
    mask_windows = window_partition(img_mask, self.window_size)  # nW, window_size, window_size, 1
  File "S:\StabilityMatrix\Packages\Stable Diffusion WebUI\venv\lib\site-packages\timm\models\swin_transformer_v2.py", line 44, in window_partition
    x = x.view(B, H // window_size[0], window_size[0], W // window_size[1], window_size[1], C)
RuntimeError: shape '[1, 3, 8, 3, 8, 1]' is invalid for input of size 784

**To Reproduce**
Load any swin tagger, for example wd-swinv2-tagger-v3

**Environment (please complete the following information):**
 - OS: Windows
 - Browser: chrome
 - Version of SD WebUI: v1.9.4, by AUTOMATIC1111
 - Version of this app: v0.3.4

Did a clean installation of sd-webui, just in case. No difference
Also some aesthetic scorers are not working due to different errors:
AttributeError: 'Paths' object has no attribute 'models_path'. Did you mean: 'model_path'?

**Comment by matcordero** [comment]
I'm from the future and I come to leave what worked for me for people who also fail, go to the folder (this is in reforge although auto1111 must have a similar path) stable-diffusion-webui-reForge\venv\Lib\site-packages and delete the current timm and in the requirements_news file add or replace the timm with this, timm==0.6.13. It is a version compatible with the extension and should work. This can happen for example when installing controlnet that its extension downloads by default another version of timm that becomes incompatible with the "tagger", so if you have this or any extension that updates the timm I recommend deleting it if you want to use the tagger, reforge comes with its own version of controlnet, so it should not be necessary to download a separate controlnet
