### ISSUE TITLE
Can't run Interrogator

### ISSUE THREAD

**Issue by WildSlowpoke** [toshiaki1729/stable-diffusion-webui-dataset-tag-editor#30]
```
Traceback (most recent call last):
  File "C:\Users\dmitr\Documents\Ai\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 321, in run_predict
    output = await app.blocks.process_api(
  File "C:\Users\dmitr\Documents\Ai\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1015, in process_api
    result = await self.call_function(fn_index, inputs, iterator, request)
  File "C:\Users\dmitr\Documents\Ai\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 856, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\dmitr\Documents\Ai\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\dmitr\Documents\Ai\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\dmitr\Documents\Ai\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Users\dmitr\Documents\Ai\stable-diffusion-webui\extensions\stable-diffusion-webui-dataset-tag-editor\scripts\main.py", line 405, in interrogate_selected_image_clip
    from scripts.dataset_tag_editor.dataset_tag_editor import interrogate_image_clip
ModuleNotFoundError: No module named 'scripts.dataset_tag_editor'
```

**Comment by toshiaki1729** [comment]
Sorry for inconvenience!

**Comment by WildSlowpoke** [comment]
I'm sorry I'm really not skilled with coding, do I just download that file and replace it with what's in my folder?

**Comment by toshiaki1729** [comment]
If tag-editor git repository is in your extensions folder, you can see tag-editor listed and can update it by click the button.
![ss2](https://user-images.githubusercontent.com/116595002/210260569-f8837976-74f6-4530-9659-54c270905502.png)

**Comment by toshiaki1729** [comment]
If not listed, I recommend you to remove tag-editor and re-install it from "Extensions" tab.
![ss](https://user-images.githubusercontent.com/116595002/210260561-aae4c2ce-3afc-411d-b599-4def555c93cd.png)

**Comment by WildSlowpoke** [comment]
Oh I'm dumb, you released the commit like 10 minutes ago, updated and it seems to be working again, thanks for the help!
