### ISSUE TITLE
ValueError: File cannot be fetched

### ISSUE THREAD

**Issue by Rartist** [toshiaki1729/stable-diffusion-webui-dataset-tag-editor#42]
Hello toshiaki,
It looks like the way the extension is handling Temp data now isn't very user friendly.
`
ValueError: File cannot be fetched: C:/A/B/. All files must contained within the Gradio python app working directory, or be a temp file created by the Gradio python app.`

That temp file's are created while the extension is used is not a problem per se - it would be great to be able to set a custom temp folder though (or use the one already specified in tha A1 repo).

The way it is I would have to move all of my datasets to a new location.

**Comment by toshiaki1729** [comment]
I'm sorry but I cannot reproduce your errors on Windows, WSL and remote Linux (Paperspace) w/ or w/o webui's "Directory for temporary images" settings .
Could you tell me the more detailed conditions under which the error occurs?

**Comment by Rartist** [comment]
It happens when I try to load a folder. It didn't happen with older versions (1 or 2 weeks ago, probably before the Temp rework).
I tried two different folders with Subfolders and both don't get loaded.
The folders are probably not in the "Gradio python app working directory" (I'm not even sure which directory that is supposed to be).

```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "E:\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "E:\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "E:\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\fastapi\applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "E:\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "E:\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "E:\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "E:\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "E:\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\gzip.py", line 43, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "E:\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "E:\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "E:\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "E:\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "E:\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\starlette\routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "E:\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "E:\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "E:\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\fastapi\routing.py", line 235, in app
    raw_response = await run_endpoint_function(
  File "E:\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\fastapi\routing.py", line 161, in run_endpoint_function
    return await dependant.call(**values)
  File "E:\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 286, in file
    raise ValueError(
ValueError: File cannot be fetched: E:/A/B/. All files must contained within the Gradio python app working directory, or be a temp file created by the Gradio python app.
```

**Comment by toshiaki1729** [comment]
This issue may be related to https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/7028
(I haven't tried it on versions earlier than https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/50059ea661b63967b217e687819cf7a9081e4a0c yet.)

**Comment by toshiaki1729** [comment]
Anyway, I'm gonna make first-aid commit by making option to use temp files for gallery images.

**Comment by toshiaki1729** [comment]
> I'm gonna make first-aid commit by adding option to use temp files for gallery images.

This is enabled in c01f7c54f785a07aa30da6870712b47b10b4e5ea.

However, though I'm not sure, 77a4c42ab022c6d643356eaecd4743a3da16ba6a may enables loading without the temp files, I hope so.
