### ISSUE TITLE
Fresh reinstall and getting BLIP errors

### ISSUE THREAD

**Issue by Omegadarling** [toshiaki1729/stable-diffusion-webui-dataset-tag-editor#58]
Works fine if I use any of the wd-v1.4... taggers, but BLIP gives me this output:

[tag-editor] Loading dataset from \\IO2\Backup\Automatic1111\Training\Specific Artists\Muhammed Sajid on Behance\JPEG
[tag-editor] Total 40 files under the directory including not image files.
load checkpoint from C:\Automatic1111\models\BLIP\model_base_caption_capfilt_large.pth
Traceback (most recent call last):
  File "C:\Automatic1111\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Automatic1111\venv\lib\site-packages\gradio\blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "C:\Automatic1111\venv\lib\site-packages\gradio\blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Automatic1111\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Automatic1111\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Automatic1111\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Automatic1111\extensions\stable-diffusion-webui-dataset-tag-editor\scripts\ui\block_load_dataset.py", line 77, in load_files_from_dir
    dte_instance.load_dataset(dir, caption_file_ext, recursive, load_caption_from_filename, interrogate_method, use_interrogator_names, threshold_booru, threshold_waifu, opts.dataset_editor_use_temp_files, kohya_json_path if use_kohya_metadata else None)
  File "C:\Automatic1111\extensions\stable-diffusion-webui-dataset-tag-editor\scripts\dataset_tag_editor\dte_logic.py", line 577, in load_dataset
    interrogate_tags += cap.predict(img)
  File "C:\Automatic1111\extensions\stable-diffusion-webui-dataset-tag-editor\scripts\dataset_tag_editor\captioning.py", line 26, in predict
    tags = shared.interrogator.generate_caption(image).split(',')
  File "C:\Automatic1111\modules\interrogate.py", line 183, in generate_caption
    caption = self.blip_model.generate(gpu_image, sample=False, num_beams=shared.opts.interrogate_clip_num_beams, min_length=shared.opts.interrogate_clip_min_length, max_length=shared.opts.interrogate_clip_max_length)
  File "C:\Automatic1111\repositories\BLIP\models\blip.py", line 156, in generate
    outputs = self.text_decoder.generate(input_ids=input_ids,
  File "C:\Automatic1111\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Automatic1111\venv\lib\site-packages\transformers\generation\utils.py", line 1490, in generate
    return self.beam_search(
  File "C:\Automatic1111\venv\lib\site-packages\transformers\generation\utils.py", line 2749, in beam_search
    outputs = self(
  File "C:\Automatic1111\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Automatic1111\repositories\BLIP\models\med.py", line 886, in forward
    outputs = self.bert(
  File "C:\Automatic1111\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Automatic1111\repositories\BLIP\models\med.py", line 781, in forward
    encoder_outputs = self.encoder(
  File "C:\Automatic1111\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Automatic1111\repositories\BLIP\models\med.py", line 445, in forward
    layer_outputs = layer_module(
  File "C:\Automatic1111\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Automatic1111\repositories\BLIP\models\med.py", line 361, in forward
    cross_attention_outputs = self.crossattention(
  File "C:\Automatic1111\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Automatic1111\repositories\BLIP\models\med.py", line 277, in forward
    self_outputs = self.self(
  File "C:\Automatic1111\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Automatic1111\repositories\BLIP\models\med.py", line 178, in forward
    attention_scores = torch.matmul(query_layer, key_layer.transpose(-1, -2))
RuntimeError: The size of tensor a (9) must match the size of tensor b (81) at non-singleton dimension 0

**Comment by toshiaki1729** [comment]
Thank you for reporting.
Does the error show when using BLIP from webUI img2img tab?

**Comment by toshiaki1729** [comment]
This extension uses built-in BLIP interrogator in webUI.
If the same error occurs when using it from img2img, removing `models\BLIP\model_base_caption_capfilt_large.pth` and restarting webUI may fix the problem.

**Comment by Vigilence** [comment]
I believe this may be a conflict with the new dreambooth extension which requires transformers~=4.27.1, which already conflicts with the clip interrogator (requires transformers~=4.26.1), which gives the same error as above.

**Comment by Vigilence** [comment]
@Omegadarling The clip interrogator already updated their end to utilize 4.27.1, so we just need this to do the same and hopefully no conflicts.
