### ISSUE TITLE
changing num_beams to anything other then 1 gives a runtime error.

### ISSUE THREAD

**Issue by Vigilence** [toshiaki1729/stable-diffusion-webui-dataset-tag-editor#61]
I noticed that prior to the update that I could set the number of beams to 12 for greater accuracy.  Currently blip interrogator only works with a number of 1 beams, or I would get an error.

`To create a public link, set `share=True` in `launch()`.
Startup time: 9.9s (list extensions: 4.8s, load scripts: 1.2s, create ui: 3.5s, gradio launch: 0.2s).
[tag-editor] Loading dataset from E:\Artists\randomart\Images\Revised Captions\Revised Images\1024
[tag-editor] Total 532 files under the directory including not image files.
[tag-editor] Loading Completed: 266 images found
Traceback (most recent call last):
  File "E:\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "E:\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "E:\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "E:\Automatic1111\stable-diffusion-webui\extensions\stable-diffusion-webui-dataset-tag-editor\scripts\ui\tab_edit_caption_of_selected_image.py", line 141, in interrogate_selected_image
    return dte_module.interrogate_image(dataset_gallery.selected_path, interrogator_name, threshold_booru, threshold_waifu)
  File "E:\Automatic1111\stable-diffusion-webui\extensions\stable-diffusion-webui-dataset-tag-editor\scripts\dataset_tag_editor\dte_logic.py", line 40, in interrogate_image
    res = cap.predict(img)
  File "E:\Automatic1111\stable-diffusion-webui\extensions\stable-diffusion-webui-dataset-tag-editor\scripts\dataset_tag_editor\captioning.py", line 26, in predict
    tags = shared.interrogator.generate_caption(image).split(',')
  File "E:\Automatic1111\stable-diffusion-webui\modules\interrogate.py", line 183, in generate_caption
    caption = self.blip_model.generate(gpu_image, sample=False, num_beams=shared.opts.interrogate_clip_num_beams, min_length=shared.opts.interrogate_clip_min_length, max_length=shared.opts.interrogate_clip_max_length)
  File "E:\Automatic1111\stable-diffusion-webui\repositories\BLIP\models\blip.py", line 156, in generate
    outputs = self.text_decoder.generate(input_ids=input_ids,
  File "E:\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "E:\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\transformers\generation\utils.py", line 1490, in generate
    return self.beam_search(
  File "E:\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\transformers\generation\utils.py", line 2749, in beam_search
    outputs = self(
  File "E:\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\Automatic1111\stable-diffusion-webui\repositories\BLIP\models\med.py", line 886, in forward
    outputs = self.bert(
  File "E:\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\Automatic1111\stable-diffusion-webui\repositories\BLIP\models\med.py", line 781, in forward
    encoder_outputs = self.encoder(
  File "E:\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\Automatic1111\stable-diffusion-webui\repositories\BLIP\models\med.py", line 445, in forward
    layer_outputs = layer_module(
  File "E:\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\Automatic1111\stable-diffusion-webui\repositories\BLIP\models\med.py", line 361, in forward
    cross_attention_outputs = self.crossattention(
  File "E:\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\Automatic1111\stable-diffusion-webui\repositories\BLIP\models\med.py", line 277, in forward
    self_outputs = self.self(
  File "E:\Automatic1111\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\Automatic1111\stable-diffusion-webui\repositories\BLIP\models\med.py", line 178, in forward
    attention_scores = torch.matmul(query_layer, key_layer.transpose(-1, -2))
RuntimeError: The size of tensor a (12) must match the size of tensor b (144) at non-singleton dimension 0`

![2023-03-22_3-37-22](https://user-images.githubusercontent.com/22781570/226832850-05381472-6321-4029-82f9-74b2ee7b2030.jpg)
![2023-03-22_3-37-01](https://user-images.githubusercontent.com/22781570/226832854-4d2fbae5-0bd6-47d9-87f7-5157affd0cfc.jpg)
![2023-03-22_3-36-31](https://user-images.githubusercontent.com/22781570/226832855-89d01523-ae3a-47de-9176-f6dfe1de5fb6.jpg)

**Comment by Vigilence** [comment]
The issue actually occurs from installing clip interrogator, which has a conflict with the built in blip interrogator, which in turns messes with the dataset tag editor.
