### ISSUE TITLE
extension broken on A1111 commit: 8d2c582e  •  checkpoint: fafc72c6fd

### ISSUE THREAD

**Issue by ShaguarWKL** [toshiaki1729/stable-diffusion-webui-dataset-tag-editor#62]
``` Error executing callback ui_tabs_callback for C:\Users\warre\AI\WebUI - Automatic1111\extensions\stable-diffusion-webui-dataset-tag-editor\scripts\main.py
Traceback (most recent call last):
  File "C:\Users\warre\AI\WebUI - Automatic1111\modules\script_callbacks.py", line 125, in ui_tabs_callback
    res += c.callback() or []
  File "C:\Users\warre\AI\WebUI - Automatic1111\extensions\stable-diffusion-webui-dataset-tag-editor\scripts\main.py", line 327, in on_ui_tabs
    ui.load_dataset.set_callbacks(o_update_filter_and_gallery,ui.toprow, ui.dataset_gallery, ui.filter_by_tags, ui.filter_by_selection, ui.batch_edit_captions, update_filter_and_gallery)
  File "C:\Users\warre\AI\WebUI - Automatic1111\extensions\stable-diffusion-webui-dataset-tag-editor\scripts\ui\block_load_dataset.py", line 91, in set_callbacks
    self.btn_load_datasets.click(
  File "C:\Users\warre\AI\WebUI - Automatic1111\venv\lib\site-packages\gradio\events.py", line 129, in __call__
    dep, dep_index = self.trigger.set_event_trigger(
  File "C:\Users\warre\AI\WebUI - Automatic1111\venv\lib\site-packages\gradio\blocks.py", line 195, in set_event_trigger
    check_function_inputs_match(fn, inputs, inputs_as_dict)
  File "C:\Users\warre\AI\WebUI - Automatic1111\venv\lib\site-packages\gradio\utils.py", line 940, in check_function_inputs_match
    if not is_special_typed_parameter(name):
  File "C:\Users\warre\AI\WebUI - Automatic1111\venv\lib\site-packages\gradio\utils.py", line 929, in is_special_typed_parameter
    is_event_data = issubclass(parameter_types.get(name, int), EventData)
TypeError: issubclass() arg 1 must be a class

Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 16.6s (import gradio: 2.0s, import ldm: 2.8s, other imports: 1.8s, list extensions: 1.6s, setup codeformer: 0.1s, load scripts: 3.2s, load SD checkpoint: 4.4s, create ui: 0.6s, gradio launch: 0.1s).
```

I'm assuming new gradio version broke this extension from my little understanding.

**Comment by toshiaki1729** [comment]
All buttons fails to add callback functions🤔

**Comment by toshiaki1729** [comment]
The error seems to occur when the call back function is containing List[str] type annotation.

**Comment by toshiaki1729** [comment]
gradio came to check if the argument of callback function is derived from `EventData` in https://github.com/gradio-app/gradio/commit/95bf08b2e29448f64e1e892200a014310ffc6d76.
But it is not compatible with type hint feature.

The related issue in gradio repo is below.
https://github.com/gradio-app/gradio/issues/3514

**Comment by toshiaki1729** [comment]
Just disabled type hint for now.
These can be replaced with `list[str]` (and it may be compatible with gradio), but there are some users using `Python <3.9` (#2 #3 #8).
Honestly, I don't think there is no need to keep compatibility with old Python, since the webUI is officially supporting `Python 3.10.6`. 
However, though I'm not sure, some cloud environments are still using Python<=3.8 and it may not be changed by user (really??)

**Comment by toshiaki1729** [comment]
Another problem. Filters are not working (apparently).
