### ISSUE TITLE
UTF-8 'Invalid Continuation Byte'

### ISSUE THREAD

**Issue by Luke-L** [toshiaki1729/stable-diffusion-webui-dataset-tag-editor#74]
Here is the webui info for my version: 

- python: 3.10.9 torch: 1.13.1+cu117 
- xformers: N/A 
- gradio: 3.23.0 
- commit: [22bcc7be]

And the error which I have honestly no idea where to start with fixing.
```
[tag-editor] Total 1282 files under the directory including not image files.
Traceback (most recent call last):
  File "B:\Github\stable-diffusion-webui322\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "B:\Github\stable-diffusion-webui322\venv\lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "B:\Github\stable-diffusion-webui322\venv\lib\site-packages\gradio\blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "B:\Github\stable-diffusion-webui322\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "B:\Github\stable-diffusion-webui322\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "B:\Github\stable-diffusion-webui322\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "B:\Github\stable-diffusion-webui322\extensions\stable-diffusion-webui-dataset-tag-editor-0.2.0\scripts\ui\block_load_dataset.py", line 80, in load_files_from_dir
    dte_instance.load_dataset(dir, caption_file_ext, recursive, load_caption_from_filename, replace_new_line, interrogate_method, use_interrogator_names, threshold_booru, threshold_waifu, opts.dataset_editor_use_temp_files, kohya_json_path if use_kohya_metadata else None)
  File "B:\Github\stable-diffusion-webui322\extensions\stable-diffusion-webui-dataset-tag-editor-0.2.0\scripts\dataset_tag_editor\dte_logic.py", line 570, in load_dataset
    taglists = load_captions(imgpaths)
  File "B:\Github\stable-diffusion-webui322\extensions\stable-diffusion-webui-dataset-tag-editor-0.2.0\scripts\dataset_tag_editor\dte_logic.py", line 534, in load_captions
    caption_text = text_path.read_text('utf8')
  File "C:\Users\games\AppData\Local\Programs\Python\Python310\lib\pathlib.py", line 1135, in read_text
    return f.read()
  File "C:\Users\games\AppData\Local\Programs\Python\Python310\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe4 in position 236: invalid continuation byte
```

**Comment by Luke-L** [comment]
nvm, i just converted the txt files into utf8
