### ISSUE TITLE
module 'scripts.ui' has no attribute 'toprow'

### ISSUE THREAD

**Issue by mykeehu** [toshiaki1729/stable-diffusion-webui-dataset-tag-editor#79]
Today I got this message when the webui loaded:
```
Traceback (most recent call last):
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\modules\script_callbacks.py", line 151, in ui_tabs_callback
    res += c.callback() or []
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\extensions\stable-diffusion-webui-dataset-tag-editor\scripts\main.py", line 210, in on_ui_tabs
    ui.toprow.create_ui(cfg_general)
AttributeError: module 'scripts.ui' has no attribute 'toprow'
```

![image](https://github.com/toshiaki1729/stable-diffusion-webui-dataset-tag-editor/assets/6390413/2c2a8d85-2609-423a-965c-21ed954a18b6)

**Comment by shengjie110** [comment]
I had the same problem

**Comment by Anna-Shcherbakova** [comment]
I had the same problem too

**Comment by kuzman123** [comment]
Me too.
