### ISSUE TITLE
TypeError: a bytes-like object is required, not 'str'`

### ISSUE THREAD

**Issue by minermanb** [toshiaki1729/stable-diffusion-webui-dataset-tag-editor#82]
`[tag-editor] Loading dataset from C:\dataset\
[tag-editor] Total 820 files under the directory including not image files.
[tag-editor] Loading Completed: 410 images found
Traceback (most recent call last):
  File "F:\sd2\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 414, in run_predict
    output = await app.get_blocks().process_api(
  File "F:\sd2\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1326, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "F:\sd2\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1260, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "F:\sd2\stable-diffusion-webui\venv\lib\site-packages\gradio\components.py", line 4411, in postprocess
    file = processing_utils.save_pil_to_file(img)
  File "F:\sd2\stable-diffusion-webui\venv\lib\site-packages\gradio\processing_utils.py", line 86, in save_pil_to_file
    pil_image.save(file_obj, pnginfo=get_pil_metadata(pil_image))
  File "F:\sd2\stable-diffusion-webui\venv\lib\site-packages\PIL\Image.py", line 2432, in save
    save_handler(self, fp, filename)
  File "F:\sd2\stable-diffusion-webui\venv\lib\site-packages\PIL\PngImagePlugin.py", line 1318, in _save
    data = name + b"\0\0" + zlib.compress(icc)
TypeError: a bytes-like object is required, not 'str'`

**Comment by minermanb** [comment]
Seems to be related to metadata.

**Comment by toshiaki1729** [comment]
Cannot reproduce this issue as far as in my environment.
Is this still an issue?
