### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'deepdanbooru_projects_path'

### ISSUE THREAD

**Issue by DuckersMcQuack** [toshiaki1729/stable-diffusion-webui-dataset-tag-editor#84]
Error executing callback ui_tabs_callback for H:\Stablediff\Automatic1111\WebuiDuckers\webui\extensions\stable-diffusion-webui-wd14-tagger\scripts\tagger.py
Traceback (most recent call last):
  File "H:\Stablediff\Automatic1111\WebuiDuckers\webui\modules\script_callbacks.py", line 151, in ui_tabs_callback
    res += c.callback() or []
  File "H:\Stablediff\Automatic1111\WebuiDuckers\webui\extensions\stable-diffusion-webui-wd14-tagger\tagger\ui.py", line 329, in on_ui_tabs
    interrogator_names = utils.refresh_interrogators()
  File "H:\Stablediff\Automatic1111\WebuiDuckers\webui\extensions\stable-diffusion-webui-wd14-tagger\tagger\utils.py", line 70, in refresh_interrogators
    for path in os.scandir(shared.cmd_opts.deepdanbooru_projects_path):
AttributeError: 'Namespace' object has no attribute 'deepdanbooru_projects_path'

**Comment by toshiaki1729** [comment]
>extensions\stable-diffusion-webui-wd14-tagger

I think you may be wrong to report here.
