### ISSUE TITLE
PermissionError: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by ziat007** [toshiaki1729/stable-diffusion-webui-dataset-tag-editor#87]
I am attempting to export a kohya metadata json but getting this error.

```
[tag-editor] Loading dataset from D:\StableDiffusion\TestModel5\BreastVeins32 - Copy
[tag-editor] Total 664 files under the directory including not image files.
[tag-editor] Loading Completed: 331 images found
[tag-editor] Backup text files: 331/331 under D:\StableDiffusion\TestModel5\BreastVeins32 - Copy
[tag-editor] Saved text files: 331/331 under D:\StableDiffusion\TestModel5\BreastVeins32 - Copy
Traceback (most recent call last):
  File "D:\StableDiffusion\A1111\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\StableDiffusion\A1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "D:\StableDiffusion\A1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\StableDiffusion\A1111\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\StableDiffusion\A1111\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "D:\StableDiffusion\A1111\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\StableDiffusion\A1111\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "D:\StableDiffusion\A1111\stable-diffusion-webui\extensions\stable-diffusion-webui-dataset-tag-editor\scripts\tag_editor_ui\block_toprow.py", line 39, in save_all_changes
    dte_instance.save_dataset(backup, load_dataset.caption_file_ext, save_kohya_metadata, metadata_output, metadata_input, metadata_overwrite, metadata_as_caption, metadata_use_fullpath)
  File "D:\StableDiffusion\A1111\stable-diffusion-webui\extensions\stable-diffusion-webui-dataset-tag-editor\scripts\dataset_tag_editor\dte_logic.py", line 651, in save_dataset
    kohya_metadata.write(dataset=self.dataset, dataset_dir=self.dataset_dir, out_path=meta_out_path, in_path=meta_in_path, overwrite=meta_overwrite, save_as_caption=meta_as_caption, use_full_path=meta_full_path)
  File "D:\StableDiffusion\A1111\stable-diffusion-webui\extensions\stable-diffusion-webui-dataset-tag-editor\scripts\dataset_tag_editor\kohya_finetune_metadata.py", line 42, in write
    with open(out_path, 'w', encoding='utf-8', newline='') as f:
PermissionError: [Errno 13] Permission denied: 'D:\\StableDiffusion\\A1111\\stable-diffusion-webui\\DATASET'

```

**Comment by ziat007** [comment]
solved it by directing it into the root directory of a1111 with just "randomname.json" as the input directory.
